version: "3.7"

services:
  front:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      target: development
    container_name: front
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    networks:
      - app
  proxy:
    image: proxy
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
      target: development
    container_name: proxy
    ports:
      - 80:80
    networks:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - front
networks:
  app:
    driver: bridge
